# Generated by Django 6.0.7 on 2026-07-13 03:17

import apps.orders.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage'),
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created_at',), 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('id',), 'verbose_name': 'Sản phẩm trong đơn', 'verbose_name_plural': 'Sản phẩm trong đơn'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ice',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='sugar',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_note',
            field=models.TextField(blank=True, verbose_name='Ghi chú giao hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng')], default='COD', max_length=30, verbose_name='Phương thức thanh toán'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Chưa thanh toán'), ('PENDING', 'Chờ xác nhận'), ('PAID', 'Đã thanh toán'), ('FAILED', 'Thanh toán thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='UNPAID', max_length=30, verbose_name='Trạng thái thanh toán'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ice_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mức đá'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_slug',
            field=models.CharField(blank=True, max_length=220, verbose_name='Slug sản phẩm'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sugar_label',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mức đường'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topping_total',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Tổng topping mỗi sản phẩm'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=150, verbose_name='Tên người nhận'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Giảm giá'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=apps.orders.models.generate_order_code, editable=False, max_length=30, unique=True, verbose_name='Mã đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_fee',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Phí giao hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('PREPARING', 'Đang pha chế'), ('READY', 'Sẵn sàng giao'), ('DELIVERING', 'Đang giao'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=30, verbose_name='Trạng thái đơn hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='stores.store', verbose_name='Cửa hàng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Tạm tính'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Tổng thanh toán'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.PositiveBigIntegerField(verbose_name='Thành tiền'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=200, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='toppings',
            field=models.JSONField(blank=True, default=list, verbose_name='Topping'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveBigIntegerField(verbose_name='Đơn giá sản phẩm'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kích thước'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_code'], name='orders_orde_order_c_cd5b49_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_phone'], name='orders_orde_custome_59f5e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='order_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='order_subtotal_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='order_item_line_total_gte_0'),
        ),
    ]
