# Generated by Django 6.0.7 on 2026-07-13 03:45

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage'),
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('created_at',), 'verbose_name': 'Lịch sử trạng thái đơn', 'verbose_name_plural': 'Lịch sử trạng thái đơn'},
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='order_item_quantity_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='order_item_line_total_gte_0',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Thời gian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='new_status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('PREPARING', 'Đang pha chế'), ('READY', 'Sẵn sàng giao'), ('DELIVERING', 'Đang giao'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], default=datetime.datetime.now, max_length=30, verbose_name='Trạng thái mới'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='old_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Chờ xác nhận'), ('CONFIRMED', 'Đã xác nhận'), ('PREPARING', 'Đang pha chế'), ('READY', 'Sẵn sàng giao'), ('DELIVERING', 'Đang giao'), ('COMPLETED', 'Hoàn thành'), ('CANCELLED', 'Đã hủy')], max_length=30, verbose_name='Trạng thái cũ'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_4ba133_idx'),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Đơn hàng'),
        ),
    ]
