# Generated by Django 6.0.7 on 2026-07-14 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_repair_order_status_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_orders', to=settings.AUTH_USER_MODEL, verbose_name='Thu ngân'),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('DELIVERY', 'Giao hàng'), ('PICKUP', 'Khách tự đến lấy'), ('DINE_IN', 'Dùng tại quán')], default='DELIVERY', max_length=20, verbose_name='Hình thức nhận hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('ONLINE', 'Website'), ('POS', 'Bán tại quầy')], default='ONLINE', max_length=20, verbose_name='Nguồn đơn hàng'),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Số bàn'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Thanh toán khi nhận hàng'), ('BANK_TRANSFER', 'Chuyển khoản ngân hàng'), ('CASH', 'Tiền mặt tại quầy')], default='COD', max_length=30, verbose_name='Phương thức thanh toán'),
        ),
    ]
