# Generated by Django 6.0.7 on 2026-07-15 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage'),
        ('orders', '0005_order_cashier_order_fulfillment_type_order_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant', verbose_name='Biến thể sản phẩm'),
        ),
    ]
