# Generated by Django 6.0.7 on 2026-07-16 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_product_variant'),
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shifts.workshift', verbose_name='Ca làm việc'),
        ),
    ]
