# Generated by Django 6.0.7 on 2026-07-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mã giảm giá'),
        ),
    ]
