# Generated by Django 6.0.7 on 2026-07-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_discount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Giảm giá từ điểm thưởng'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_points_used',
            field=models.PositiveIntegerField(default=0, verbose_name='Điểm thưởng đã dùng'),
        ),
    ]
