# Generated by Django 6.0.7 on 2026-07-13 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150, verbose_name='Tên người nhận')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('address_line', models.CharField(max_length=255, verbose_name='Địa chỉ chi tiết')),
                ('ward', models.CharField(blank=True, max_length=100, verbose_name='Phường/Xã')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Quận/Huyện')),
                ('province', models.CharField(blank=True, max_length=100, verbose_name='Tỉnh/Thành phố')),
                ('label', models.CharField(blank=True, help_text='Ví dụ: Nhà, Công ty', max_length=30, verbose_name='Nhãn địa chỉ')),
                ('delivery_note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú giao hàng')),
                ('is_default', models.BooleanField(default=False, verbose_name='Địa chỉ mặc định')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
                'ordering': ('-is_default', '-updated_at'),
            },
        ),
    ]
