# Generated by Django 6.0.7 on 2026-07-16 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Đang mở'), ('CLOSED', 'Đã đóng')], default='OPEN', max_length=20, verbose_name='Trạng thái')),
                ('opening_cash', models.PositiveBigIntegerField(default=0, verbose_name='Tiền mặt đầu ca')),
                ('expected_cash', models.PositiveBigIntegerField(default=0, verbose_name='Tiền mặt dự kiến')),
                ('actual_cash', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Tiền mặt thực tế')),
                ('cash_difference', models.BigIntegerField(default=0, verbose_name='Chênh lệch tiền mặt')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Mở ca lúc')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Đóng ca lúc')),
                ('opening_note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú mở ca')),
                ('closing_note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú đóng ca')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_shifts', to='stores.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'ordering': ('-opened_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('store', 'cashier'), name='unique_open_shift_per_store_cashier'), models.CheckConstraint(condition=models.Q(('opening_cash__gte', 0)), name='shift_opening_cash_gte_0'), models.CheckConstraint(condition=models.Q(('expected_cash__gte', 0)), name='shift_expected_cash_gte_0')],
            },
        ),
    ]
