# Generated by Django 6.0.7 on 2026-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        ('orders', '0008_order_voucher_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loyaltytransaction',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='tier',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], default='MEMBER', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('transaction_type', 'EARN')), fields=('order', 'transaction_type'), name='unique_order_loyalty_earn'),
        ),
    ]
