# Generated by Django 6.0.7 on 2026-07-16 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_loyalty_schema'),
        ('orders', '0009_order_loyalty_discount_order_loyalty_points_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('transaction_type', 'REDEEM')), fields=('account', 'order', 'transaction_type'), name='unique_loyalty_redeem_per_order'),
        ),
    ]
