# Generated by Django 6.0.7 on 2026-07-16 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0008_order_voucher_code'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã giảm giá')),
                ('name', models.CharField(max_length=150, verbose_name='Tên chương trình')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('discount_type', models.CharField(choices=[('FIXED', 'Giảm số tiền cố định'), ('PERCENT', 'Giảm theo phần trăm')], max_length=20, verbose_name='Loại giảm giá')),
                ('discount_value', models.PositiveBigIntegerField(help_text='Nếu giảm phần trăm, nhập từ 1 đến 100.', verbose_name='Giá trị giảm')),
                ('maximum_discount', models.PositiveBigIntegerField(blank=True, help_text='Chỉ áp dụng cho giảm theo phần trăm.', null=True, verbose_name='Mức giảm tối đa')),
                ('minimum_order_value', models.PositiveBigIntegerField(default=0, verbose_name='Giá trị đơn tối thiểu')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Để trống nếu không giới hạn.', null=True, verbose_name='Tổng lượt sử dụng tối đa')),
                ('usage_limit_per_customer', models.PositiveIntegerField(default=1, verbose_name='Lượt dùng tối đa mỗi khách')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Số lượt đã sử dụng')),
                ('starts_at', models.DateTimeField(verbose_name='Bắt đầu lúc')),
                ('ends_at', models.DateTimeField(verbose_name='Kết thúc lúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(blank=True, help_text='Để trống nếu mã áp dụng cho tất cả cửa hàng.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='stores.store', verbose_name='Cửa hàng áp dụng')),
            ],
            options={
                'verbose_name': 'Mã giảm giá',
                'verbose_name_plural': 'Mã giảm giá',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại khách')),
                ('discount_amount', models.PositiveBigIntegerField(verbose_name='Số tiền đã giảm')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='Sử dụng lúc')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_redemption', to='orders.order', verbose_name='Đơn hàng')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotions.voucher', verbose_name='Mã giảm giá')),
            ],
            options={
                'verbose_name': 'Lượt sử dụng mã',
                'verbose_name_plural': 'Lượt sử dụng mã',
                'ordering': ('-redeemed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['code', 'is_active'], name='promotions__code_36154e_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['starts_at', 'ends_at'], name='promotions__starts__a95676_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gt', 0)), name='voucher_discount_value_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('usage_limit_per_customer__gt', 0)), name='voucher_customer_limit_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='voucher_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['voucher', 'customer'], name='promotions__voucher_ba920a_idx'),
        ),
        migrations.AddIndex(
            model_name='voucherredemption',
            index=models.Index(fields=['voucher', 'customer_phone'], name='promotions__voucher_f683f2_idx'),
        ),
    ]
