# Generated by Django 6.0.7 on 2026-07-15 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0005_order_cashier_order_fulfillment_type_order_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'ordering': ('-created_at',), 'verbose_name': 'Giao dịch kho', 'verbose_name_plural': 'Giao dịch kho'},
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='balance_after',
            preserve_default=False,
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tồn kho sau giao dịch'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='orders.order', verbose_name='Đơn hàng'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.ingredient', verbose_name='Nguyên liệu'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Số dương khi nhập/hoàn kho, số âm khi xuất bán.', max_digits=12, verbose_name='Số lượng thay đổi'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IMPORT', 'Nhập kho'), ('CONSUME', 'Xuất bán'), ('RESTORE', 'Hoàn kho'), ('ADJUST', 'Điều chỉnh')], max_length=20, verbose_name='Loại giao dịch'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('transaction_type', 'CONSUME')), fields=('order', 'ingredient', 'transaction_type'), name='unique_inventory_consume_per_order_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False), ('transaction_type', 'RESTORE')), fields=('order', 'ingredient', 'transaction_type'), name='unique_inventory_restore_per_order_ingredient'),
        ),
    ]
