# Generated by Django 6.0.7 on 2026-07-11 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=140, verbose_name='Đường dẫn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='stores.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=200, verbose_name='Đường dẫn')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ngắn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả chi tiết')),
                ('base_price', models.PositiveBigIntegerField(default=0, verbose_name='Giá cơ bản')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Ảnh sản phẩm')),
                ('has_variants', models.BooleanField(default=False, verbose_name='Có biến thể')),
                ('supports_sugar', models.BooleanField(default=False, verbose_name='Cho chọn mức đường')),
                ('supports_ice', models.BooleanField(default=False, verbose_name='Cho chọn mức đá')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Sản phẩm nổi bật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('status', models.CharField(choices=[('DRAFT', 'Bản nháp'), ('ACTIVE', 'Đang bán'), ('OUT_OF_STOCK', 'Hết hàng'), ('INACTIVE', 'Ngừng bán')], default='DRAFT', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Danh mục')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='stores.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ('-is_featured', 'name'),
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='unique_category_slug_per_store'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'slug'), name='unique_product_slug_per_store'),
        ),
    ]
