# Generated by Django 6.0.7 on 2026-07-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên topping')),
                ('price', models.PositiveBigIntegerField(default=0, verbose_name='Giá bán')),
                ('is_available', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toppings', to='stores.store', verbose_name='Cửa hàng')),
            ],
            options={
                'verbose_name': 'Topping',
                'verbose_name_plural': 'Topping',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Số lượng tối đa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_toppings', to='catalog.product', verbose_name='Sản phẩm')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_toppings', to='catalog.topping', verbose_name='Topping')),
            ],
            options={
                'verbose_name': 'Topping của sản phẩm',
                'verbose_name_plural': 'Topping của sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên biến thể')),
                ('price', models.PositiveBigIntegerField(verbose_name='Giá bán')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_default', models.BooleanField(default=False, verbose_name='Biến thể mặc định')),
                ('is_available', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'ordering': ('display_order', 'price'),
                'constraints': [models.UniqueConstraint(fields=('product', 'name'), name='unique_variant_name_per_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='topping',
            constraint=models.UniqueConstraint(fields=('store', 'name'), name='unique_topping_name_per_store'),
        ),
        migrations.AddConstraint(
            model_name='producttopping',
            constraint=models.UniqueConstraint(fields=('product', 'topping'), name='unique_topping_per_product'),
        ),
        migrations.AddConstraint(
            model_name='producttopping',
            constraint=models.CheckConstraint(condition=models.Q(('max_quantity__gt', 0)), name='product_topping_max_quantity_gt_0'),
        ),
    ]
