# Generated by Django 6.0.7 on 2026-07-12 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_topping_producttopping_productvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('SUGAR', 'Mức đường'), ('ICE', 'Mức đá')], max_length=20, verbose_name='Loại tùy chọn')),
                ('code', models.CharField(max_length=30, verbose_name='Mã')),
                ('label', models.CharField(max_length=100, verbose_name='Tên hiển thị')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lựa chọn đường và đá',
                'verbose_name_plural': 'Lựa chọn đường và đá',
                'ordering': ('option_type', 'display_order', 'label'),
                'constraints': [models.UniqueConstraint(fields=('option_type', 'code'), name='unique_option_type_and_code')],
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Lựa chọn mặc định')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option_choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_options', to='catalog.optionchoice', verbose_name='Lựa chọn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='catalog.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Tùy chọn của sản phẩm',
                'verbose_name_plural': 'Tùy chọn của sản phẩm',
                'ordering': ('option_choice__option_type', 'option_choice__display_order'),
                'constraints': [models.UniqueConstraint(fields=('product', 'option_choice'), name='unique_option_choice_per_product')],
            },
        ),
    ]
