# Generated by Django 6.0.7 on 2026-07-12 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_optionchoice_productoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Ảnh')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Mô tả ảnh')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ảnh chính')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Ảnh sản phẩm',
                'verbose_name_plural': 'Ảnh sản phẩm',
                'ordering': ('-is_primary', 'display_order', 'id'),
            },
        ),
    ]
