# Generated by Django 6.0.7 on 2026-07-13 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_repair_order_status_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField()),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('account_holder', models.CharField(blank=True, max_length=150)),
                ('qr_content', models.CharField(max_length=255)),
                ('transaction_code', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
            ],
        ),
    ]
