# Generated by Django 6.0.7 on 2026-07-13 18:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_repair_order_status_history'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveBigIntegerField(verbose_name='Số tiền')),
                ('bank_code', models.CharField(blank=True, max_length=30, verbose_name='Mã ngân hàng')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Tên ngân hàng')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản')),
                ('account_holder', models.CharField(blank=True, max_length=150, verbose_name='Chủ tài khoản')),
                ('transfer_content', models.CharField(max_length=100, verbose_name='Nội dung chuyển khoản')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Mã giao dịch ngân hàng')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('SUCCESS', 'Thành công'), ('FAILED', 'Thất bại'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=30, verbose_name='Trạng thái')),
                ('customer_submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Khách báo đã chuyển lúc')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Thanh toán lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='orders.order', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Giao dịch thanh toán',
                'verbose_name_plural': 'Giao dịch thanh toán',
                'ordering': ('-created_at',),
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='payment_pay_status_cab3ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_transaction_amount_gt_0'),
        ),
    ]
